version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mysql
      - DB_NAME=time_tracker_db
    ports:
      - "9080:9080"
    restart: always
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - time-tracker:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  time-tracker:

